import type { FeedItem } from "@/lib/types";

export const demoItems: FeedItem[] = [
  {
    id: "1",
    title: "Next.js 15 & React 19: Architectural changes and server performance",
    excerpt: "An in-depth breakdown of async request handling, server actions optimization, and static rendering improvements in modern web development.",
    url: "https://nextjs.org/blog",
    source: "Next.js Blog",
    author: "Vercel Team",
    publishedAt: "2026-09-04T04:00:00.000Z",
    interests: ["Next.js", "React"],
    sourceCount: 4,
    engagementCount: 3200,
    saved: false,
    read: false,
    explanation: ["Matches Next.js", "From 4 tracked sources"],
  },
  {
    id: "2",
    title: "PostgreSQL row-level security patterns for multi-tenant applications",
    excerpt: "Best practices for configuring RLS policies, performance indexing, and token validation in production databases.",
    url: "https://supabase.com/blog",
    source: "Supabase Blog",
    author: "Supabase Team",
    publishedAt: "2026-08-27T15:00:00.000Z",
    interests: ["Supabase", "GitHub"],
    sourceCount: 2,
    engagementCount: 1850,
    saved: true,
    read: false,
    explanation: ["Matches Supabase", "Published recently"],
  },
  {
    id: "3",
    title: "OpenAI models, prompt engineering, and context window optimization",
    excerpt: "Exploring determinism, error recovery, and context compaction techniques when deploying autonomous coding agents.",
    url: "https://openai.com/news/",
    source: "OpenAI News",
    author: "OpenAI Team",
    publishedAt: "2026-08-26T09:10:00.000Z",
    interests: ["OpenAI", "Vercel"],
    sourceCount: 3,
    engagementCount: 940,
    saved: false,
    read: true,
    explanation: ["Matches OpenAI", "From 3 tracked sources"],
  },
  {
    id: "4",
    title: "TypeScript 5.5 release notes and static analysis improvements",
    excerpt: "Improved type checking performance, inferred type predicates, and refined declaration file generation.",
    url: "https://devblogs.microsoft.com/typescript/",
    source: "TypeScript Blog",
    author: "Microsoft TypeScript Team",
    publishedAt: null,
    interests: ["TypeScript", "GitHub"],
    sourceCount: 1,
    engagementCount: 420,
    saved: false,
    read: false,
    explanation: ["Matches TypeScript", "Publication date unavailable"],
  },
];
