import type { FeedItem } from "@/lib/types";

export const demoItems: FeedItem[] = [
  {
    id: "1",
    title: "The practical shift from AI prototypes to reliable products",
    excerpt: "Teams are replacing one-off demos with measured workflows, clear evaluation sets, and observable production systems.",
    url: "https://medium.com/tag/artificial-intelligence",
    source: "Medium · Artificial Intelligence",
    author: "Nora Chen",
    publishedAt: "2026-08-28T03:30:00.000Z",
    interests: ["Artificial Intelligence", "Software Engineering"],
    sourceCount: 4,
    saved: false,
    read: false,
    explanation: ["Matches Artificial Intelligence", "From 4 tracked sources"],
  },
  {
    id: "2",
    title: "Why small developer tools are having a very good year",
    excerpt: "A new generation of focused products is winning by doing one difficult job exceptionally well.",
    url: "https://medium.com/tag/developer-tools",
    source: "Medium · Developer Tools",
    author: "Eli Morgan",
    publishedAt: "2026-08-27T15:00:00.000Z",
    interests: ["Developer Tools", "Startups"],
    sourceCount: 2,
    saved: true,
    read: false,
    explanation: ["Matches Developer Tools", "Published recently"],
  },
  {
    id: "3",
    title: "A calmer way to reason about cloud security boundaries",
    excerpt: "Start with identity, data movement, and failure domains before adding another layer of tooling.",
    url: "https://medium.com/tag/cybersecurity",
    source: "Medium · Cybersecurity",
    author: "Samira Patel",
    publishedAt: "2026-08-26T09:10:00.000Z",
    interests: ["Cybersecurity", "Cloud Computing"],
    sourceCount: 3,
    saved: false,
    read: true,
    explanation: ["Matches Cybersecurity", "From 3 tracked sources"],
  },
  {
    id: "4",
    title: "Notes on building data products people can actually trust",
    excerpt: "Trust grows from visible provenance, predictable updates, and honest handling of missing information.",
    url: "https://medium.com/tag/data-science",
    source: "Medium · Data Science",
    author: "Unknown author",
    publishedAt: null,
    interests: ["Data Science", "Software Engineering"],
    sourceCount: 1,
    saved: false,
    read: false,
    explanation: ["Matches Data Science", "Publication date unavailable"],
  },
];
